### ISSUE TITLE
Bug: `_HashMap<String, String?> is not a subtype of type Map<String, String>?`

### ISSUE THREAD

**Issue by coffeecoding** [sefidgaran/signalr_client#10]
`Unhandled exception:
type '_HashMap<String, String?>' is not a subtype of type 'Map<String, String>?' in type cast
#0      WebSupportingHttpClient._sendHttpRequest (package:signalr_netcore/web_supporting_http_client.dart:125:36)
#1      WebSupportingHttpClient.send.<anonymous closure> (package:signalr_netcore/web_supporting_http_client.dart:79:12)
#2      WebSupportingHttpClient.send.<anonymous closure> (package:signalr_netcore/web_supporting_http_client.dart:38:40)
#3      new Future.<anonymous closure> (dart:async/future.dart:174:37)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)`

**Comment by pawelpetruch** [comment]
@coffeecoding has this been resolved? I get the same issue.

**Comment by pawelpetruch** [comment]
@sefidgaran
