### ISSUE TITLE
TimeoutException after 0:00:02.000000: Future not completed

### ISSUE THREAD

**Issue by RazMuhammadAfridi** [sefidgaran/signalr_client#18]
Dear when i try to connect with server i am getting "TimeoutException after 0:00:02.000000: Future not completed" issue , please check it and if working with you then please advise how can i fix this.

Note: I am using emulator and due to that reason i am accessing the localhost with ip: 10.0.2.2

**Comment by paulsarknas1** [comment]
Hello!  I am experiencing the same issue, have you been able to resolve this?

**Comment by luizrsilva** [comment]
Hello, I've been looking at the source code, and I actually found a default timeout of 2000ms in [http_connection.dart](https://github.com/sefidgaran/signalr_client/blob/master/lib/http_connection.dart#:~:text=static%20final%20maxRequestTimeoutMilliseconds%20%3D%202000%3B)

Maybe this value can be exposed in [http_connection_options.dart](https://github.com/sefidgaran/signalr_client/blob/master/lib/http_connection_options.dart) so you can change this limit.

**Comment by Trushar88** [comment]
@RazMuhammadAfridi  Hi, I am facing the same issue, have you any solution for it?

**Comment by sefidgaran** [comment]
Thanks Luke, pull request has been merged and published. 
I am going to close this issue.
