### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding.

### ISSUE THREAD

**Issue by robertnax** [sefidgaran/signalr_client#19]
Getting this error when trying to build with Flutter version 2.10.1

Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by sefidgaran** [comment]
Thanks @robertnax for reporting this issue in the package examples. 

It is fixed now and all examples have been migrated to Android embedding V2.

I am going to close this issue.

Regards
