### ISSUE TITLE
SignalR blocking http requests on server

### ISSUE THREAD

**Issue by Farrukh997** [sefidgaran/signalr_client#23]
Hello, I have been developing an app for waiters working in restaurants. App uses signalr_netcore for listening to the state of tables from the .net server. But the developer who's developing server-side says that after connection from a mobile phone the server is blocked and can't handle HTTP requests. And blaming my app for blockage. is there any solution to that? or signal isn't meant to work alongside ordinary HTTP requests?

**Comment by jayquest** [comment]
> 

I believe the problems is the bad backend developer, what he is saying doesn't make any sense, specially because you don't request anything, you create a connection to the server and then the server push any changes to your side.
