### ISSUE TITLE
Faced the issue not receiving message callback on the latest version.

### ISSUE THREAD

**Issue by vernalclareai** [sefidgaran/signalr_client#25]
Important Note: if you are experiencing issues (for example not receiving message callback) with the latest version, please give a try to older version as signalr_netcore: 0.1.7+2-nullsafety.3 but bear in mind that this version does not support auto reconnect functionalities and need to be handled manually.

*********************
Flutter version : 2.8.1
I saw the note on the lib page, I could resolve the issue using the 0.1.7+2-nullsafety.3.

The issue is fixed on the next version?
Thanks.

**Comment by sefidgaran** [comment]
Hi @vernalclareai 

It may depends on your signalR server and setup, I can see that latest version v1.3.0 works very well.

Thanks
