### ISSUE TITLE
The underlying connection was closed before the hub handshake could complete( with accessTokenFactory)

### ISSUE THREAD

**Issue by chenshaxuanjing** [sefidgaran/signalr_client#26]
![微信截图_20220429205104](https://user-images.githubusercontent.com/32640500/165947647-f2310374-e455-40ad-a09e-a81d9709be6b.png)

**Comment by sefidgaran** [comment]
Hi @chenshaxuanjing 

Please refer to this reported issue and fix #21 .

Thanks
