### ISSUE TITLE
problem when add Authorize on .net 6 and add token on Client 

### ISSUE THREAD

**Issue by IdrisQashan** [sefidgaran/signalr_client#39]
(C# client works) and on flutter 'GeneralError (The underlying connection was closed before the hub handshake could complete.)' that happen when I add Authentication only

**Comment by Sam-fr** [comment]
Have you found a workaround?

**Comment by sefidgaran** [comment]
Closing Issue:
This issue hs been address by merge and publishing of PR #93 .
Thanks
