### ISSUE TITLE
Null Safety Request 

### ISSUE THREAD

**Issue by joeyyy688** [sefidgaran/signalr_client#8]
I would like to ask if this package will ever be migrated to null safety ??

**Comment by sefidgaran** [comment]
Hi @joeyyy688 

 There are some earlier versions that supports null safety if you look at the versions tab in:
https://pub.dev/packages/signalr_netcore/versions
Hopefully I will manage to cover null safety in latest version,
mean while for the latest version null safety migration PRs are welcomed.

**Comment by sefidgaran** [comment]
Hi @joeyyy688  Null safety migration has been done.

**Comment by joeyyy688** [comment]
@sefidgaran Thank you 🙏🏽
