### ISSUE TITLE
Upgrade sse_channel library to version 0.1.1

### ISSUE THREAD

**Issue by KevinBellAya** [sefidgaran/signalr_client#87]
The current version of sse_channel in your pubspec file is 0.0.4, which depends on uuid 3.07. However many important and widely used libraries now depend on uuid ^4.0.0. This means that this signalr library is no longer compatible with many new apps and is holding apps currently using this library back from upgrading. Please consider bumping of the version of the dependency in your pubspec file.

**Comment by mario-madrid** [comment]
Any chance to merge this?

Thanks!
