### ISSUE TITLE
Server timeout elapsed

### ISSUE THREAD

**Issue by diegorkalschne** [sefidgaran/signalr_client#92]
`Server timeout elapsed without receiving a message from the server.`

Does anyone know what I could try to modify on the server to remove this error? Or to be able to test better?

Until recently, I was successfully using the package, in the same API.
In debug mode, it works. But in release mode, it doesn't.

My code in client:
```dart
class SignalRService {
  SignalRService(this.serverUrl) {
    _hubConnection = HubConnectionBuilder()
        .withAutomaticReconnect()
        .withUrl(
          serverUrl,
          options: HttpConnectionOptions(
            requestTimeout: 60000,
          ),
        )
        .build();
  }

  late final String serverUrl;
  late final HubConnection _hubConnection;

  HubConnection get hubConnection => _hubConnection;

  Future<void> connect() async {
    await _hubConnection.start();
  }
}
```
In server:
```c#
public class MobileHub : Hub
{
//Methods
}
```
The hub is also registered in Startup.cs.

**Comment by beebobox** [comment]
@diegorkalschne : I am experiencing the same issue. Did you find a solution?

**Comment by diegorkalschne** [comment]
@beebobox 
On my Windows Server, the WebSocket protocol was not installed.
After installing it, it started working again.

See: https://secure.jadeworld.com/developer-centre/JADE2018/OnlineDocumentation/content/resources/installconfig/ch3configuringjade/iisinstallforwebsocket.htm

**Comment by MohsinIkram-Auxilium** [comment]
@diegorkalschne I'm facing same problem on Mac M1.
How can i fix it?

**Comment by diegorkalschne** [comment]
@MohsinIkram-Auxilium 
I fixed it by installing the WebSocket protocol on the server. The problem was not on the client or my machine.


> [@beebobox](https://github.com/beebobox) On my Windows Server, the WebSocket protocol was not installed. After installing it, it started working again.
> 
> See: https://secure.jadeworld.com/developer-centre/JADE2018/OnlineDocumentation/content/resources/installconfig/ch3configuringjade/iisinstallforwebsocket.htm

**Comment by MohsinIkram-Auxilium** [comment]
@diegorkalschne Thanks for your swift response. 
Let me ask this to my backend team then will get back to you..

**Comment by MohsinIkram-Auxilium** [comment]
@diegorkalschne Thanks. Its working..
